development:
  adapter: postgresql
  endcoding: utf8
  reconect: false
  database: development_appointment
  pool: 5
  username: indostrap_technologies
  password: password
  host: localhost

production:
  adapter: postgresql
  endcoding: utf8
  reconect: false
  database: appointment
  pool: 5
  username: indostrap_technologies
  password: password
  host: localhost